### ISSUE TITLE
Game Support Tracker

### ISSUE THREAD

**Issue by Medstar117** [Medstar117/cnc3-origin-mod-installer#11]
This will keep track of all games that will be added to the launcher.

- [x] Tiberium Wars
- [x] Kane's Wrath
- [ ] Tiberian Sun
- [ ] Tiberian Sun: Firestorm
- [ ] Command & Conquer
---------------------------------------
- [x] Red Alert 3
- [x] Red Alert 3: Uprising
- [ ] Red Alert 2
- [ ] Red Alert 2: Yuri's Revenge
- [ ] Red Alert
---------------------------------------
- [ ] Generals  <-------------------------------- In progress
- [ ] Generals: Zero Hour <-------------------- In progress
---------------------------------------
- [ ] Renegade
